plugins {
    id 'java'
}

description = 'OpenAudioMc Paper user adapter'

dependencies {
    implementation project(':OpenAudioMc:API')

    compileOnly libs.paper.api.adapter
    compileOnly(libs.adventure.platform.bukkit) {
        exclude module: 'adventure-bom'
        exclude module: 'adventure-api'
        exclude module: 'adventure-nbt'
    }
}
