package com.craftmend.openaudiomc.generic.networking.abstracts;

public enum PacketChannel {

    /**
     * All the channel names that are used in communication
     * <p>
     * SOCKET_IN is what the plugin receives via the client
     * SOCKET_OUT is what is send to the socket to proxy to the client
     */

    SOCKET_IN_REGISTER_CLIENT,
    SOCKET_IN_UNREGISTER_CLIENT,
    SOCKET_IN_CLIENT_ENABLED_HUE,
    SOCKET_IN_CLIENT_FAILED_MEDIA,
    SOCKET_IN_CLIENT_UPDATE_CHANNELS,
    SOCKET_IN_CLIENT_CHANGED_VOLUME,

    SOCKET_OUT_KICK_CLIENT,
    SOCKET_OUT_ACKNOWLEDGEMENT,

    CLIENT_OUT_CREATE_MEDIA,
    CLIENT_OUT_UPDATE_MEDIA,
    CLIENT_OUT_SET_PROTOCOL_VERSION,
    CLIENT_OUT_ENABLE_MODERATION,
    CLIENT_OUT_DESTROY_MEDIA,
    CLIENT_OUT_PREFETCH,
    CLIENT_OUT_PUSH_NOTIFICATION,
    CLIENT_OUT_SET_VOLUME,
    CLIENT_OUT_SET_HUE,
    CLIENT_OUT_PLAYER_LOCATION,
    CLIENT_OUT_SPEAKER_CREATE,
    CLIENT_OUT_SPEAKER_DESTROY,
    CLIENT_OUT_VOICE_UNLOCK,
    CLIENT_OUT_VOICE_BLUR,
    CLIENT_OUT_VOICE_DROP_STREAM,
    CLIENT_OUT_VOICE_UPDATE_PEER_LOCATIONS,
    CLIENT_OUT_VOICE_SUBSCRIBE,
    CLIENT_OUT_TOGGLE_MIC,
    CLIENT_OUT_TOGGLE_DEAFEN,
    CLIENT_OUT_PEER_OPTIONS,
    CLIENT_OUT_CHANNEL_LIST_PATCH,
    CLIENT_OUT_CHANNEL_STATUS,

    CLIENT_OUT_MODERATION_STATUS,

    SOCKET_IN_CLIENT_INITIALIZED_RTC,
    SOCKET_IN_CLIENT_CHANNEL_UI

}
