plugins {
    id 'java-library'
    alias libs.plugins.shadow
    alias libs.plugins.lombok
}

apply from: "$rootDir/gradle/vistas-shadow-conventions.gradle"

description = 'OpenAudioMc Vistas Client'

dependencies {
    implementation libs.lettuce.core

    compileOnly project(':OpenAudioMc:API')
    compileOnly project(':OpenAudioMc:Plugin')
    compileOnly libs.spigot.api
}

shadowJar {
    archiveBaseName = 'vistas-client'
}
