plugins {
    id 'java-library'
    alias libs.plugins.shadow
    alias libs.plugins.lombok
    id 'maven-publish'
}

apply from: "$rootDir/gradle/vistas-shadow-conventions.gradle"

description = 'OpenAudioMc Vistas Client'

dependencies {
    implementation libs.lettuce.core

    compileOnly project(':OpenAudioMc:API')
    compileOnly project(':OpenAudioMc:Plugin')
    compileOnly libs.spigot.api
}

shadowJar {
    archiveBaseName = 'vistas-client'
}

apply from: "$rootDir/gradle/publish-conventions.gradle"

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact shadowJar

            groupId = project.group
            artifactId = 'openaudiomc-vistas-client'
            version = project.version
        }
    }
}
