plugins {
    id 'java-library'
    alias libs.plugins.lombok
}

apply from: "$rootDir/gradle/publish-conventions.gradle"

description = 'OpenAudioMc API'

dependencies {
    compileOnly libs.spigot.api
    compileOnly libs.jetbrains.annotations
}

java {
    withSourcesJar()
    withJavadocJar()
}

javadoc {
    options.source = '8'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = project.group
            artifactId = 'openaudiomc-api'
            version = project.version
        }
    }
}

jar {
    archiveBaseName = 'openaudiomc-api'
}
