plugins {
    id 'java-library'
    id 'maven-publish'
    id("io.freefair.lombok") version "8.13.1"
}

description = 'OpenAudioMc API'

dependencies {
    compileOnly deps.spigot
    compileOnly deps.jetbrainsAnnot
}

java {
    withSourcesJar()
    withJavadocJar()
}

javadoc {
    options {
        source = '8'
        encoding = 'UTF-8'
        charSet = 'UTF-8'
        docEncoding = 'UTF-8'
        addStringOption('Xdoclint:none', '-quiet')
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = project.group
            artifactId = "openaudiomc-api"
            version = project.version
        }
    }

    repositories {
        maven {
            name = "pixelib-repo"
            url = uri("https://repo.mats.coffee/repository/mats-public")

            credentials {
                def settings = new XmlSlurper().parse(new File(System.getProperty("user.home"), ".m2/settings.xml"))
                def server = settings.servers.server.find { it.id.text() == "pixelib-repo" }

                username = server.username.text()
                password = server.password.text()
            }
        }
    }
}

jar {
    archiveBaseName = 'openaudiomc-api'
}
