#!/bin/bash

. smoke.sh

# check dev env
smoke_url_ok "http://cicd.openaudiomc.net"
    smoke_assert_body "bundle.js"

# check basic rest services and stuff
smoke_url_ok "http://cloud.openaudiomc.net"
    smoke_assert_body "donate"

smoke_url_ok "https://cloud.openaudiomc.net/api/v2/account-services/settings/42bba1e3-f2ff-42a9-b1b3-ff4c783d70ee"
    smoke_assert_body "LEGACY"

smoke_url_ok "https://cloud.openaudiomc.net/api/v2/account-services/settings/37545e6e-32be-48c5-b037-4a18d79014ee"
    smoke_assert_body "ACCOUNT"

smoke_url_ok "https://plus.openaudiomc.net/session"
    smoke_assert_body "GO_AWAY"
    smoke_assert_body "{"

smoke_url_ok "https://help.openaudiomc.net/"
    smoke_assert_body "github.com/Mindgamesnl"
    smoke_assert_body "Spigot"

smoke_url_ok "https://discord.openaudiomc.net"
    smoke_assert_body "discord"

smoke_url_ok "https://account.craftmend.com"
    smoke_assert_body "login"
    smoke_assert_body "register"

smoke_url_ok "https://media.openaudiomc.net"
    smoke_assert_body "Hey there!"

# check if the public build looks healthy
smoke_url_ok "http://client.openaudiomc.net/OpenAudioMc.bundle.js"
    smoke_assert_body "login"
    smoke_assert_body "hue"
    smoke_assert_body "rtc"
    smoke_assert_body "error"
    smoke_assert_body "catch"
    smoke_assert_body "try"
    smoke_assert_body "server"

smoke_url_ok "http://client.openaudiomc.net/index.html"
    smoke_assert_body "bundle.js"
    smoke_assert_body "login"
    smoke_assert_body "OpenAudioMc"
    smoke_assert_body "bundle.js"
    smoke_assert_body "script"

smoke_url_ok "http://client.openaudiomc.net/login.html"
    smoke_assert_body "minecraft"
    smoke_assert_body "input"
    smoke_assert_body "button"

smoke_report