plugins {
    id 'java-library'
    id 'application'
    alias libs.plugins.shadow
    alias libs.plugins.lombok
}

apply from: "$rootDir/gradle/vistas-shadow-conventions.gradle"

description = 'OpenAudioMc Vistas Server'

application {
    mainClass = 'com.craftmend.vistas.server.VistasBoot'
}

dependencies {
    implementation project(':OpenAudioMc:API')
    implementation project(':OpenAudioMc:Plugin')
    implementation project(':OpenAudioMc:OA-VistasClient')
    implementation libs.spigot.api
    implementation libs.wisp
    implementation libs.gson

    testImplementation libs.junit
}

shadowJar {
    archiveBaseName = 'vistas-server'

    manifest {
        attributes(
            'Main-Class': application.mainClass.get(),
            'Class-Path': 'libs/'
        )
    }
}

jar {
    enabled = false
}

test {
    forkEvery = 0
    testLogging.showStandardStreams = true
}
