plugins {
    id 'java'
}

description = 'OpenAudioMc WorldGuard 7 support'

dependencies {
    compileOnly project(':OpenAudioMc:OA-WorldguardIntegration')
    compileOnly libs.spigot.api

    // Built against a 1.17+ artifact on purpose, we only touch API that exists on 1.8+
    compileOnly libs.worldguard.modern
    compileOnly libs.worldedit.modern
}
